packages:
  - "apps/*"
  - "packages/*"

autoInstallPeers: true
packageImportMethod: copy

allowBuilds:
  "@prisma/engines": true
  "@scarf/scarf": true
  "@tailwindcss/oxide": true
  argon2: true
  esbuild: true
  msgpackr-extract: true
  prisma: true
  unrs-resolver: true